language: python
python:
  #- "2.7"
  #- "3.5"
  - "3.7"
#  - "3.8" #Errors on Travis, build times out because no output was received...

# this ubuntu distribution has sure the libopenmpi-dev packages available
dist: bionic

# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt install libopenmpi-dev openmpi-bin
  - pip install mpi4py
  - python setup.py install
  - pip install coveralls
  - pip install pathos
  - pip install numpy
  - pip install matplotlib
  - pip install pandas
  - pip install scipy
  - pip install click
  - pip install deap
  # Need to force pytest-cov to v2.6 as current version (2.6.1) is deprecated and pytest:3.10.1
  - pip install pytest==3.10.1 pytest-pep8 pytest-cov==2.6
  # Use docutils to generate html describe
  - pip install docutils
  - pip install numba
  - pip install tables


script:
  - py.test tests/test_* --cov spotpy --cov-report term-missing -v
#  - mpirun -c 4 python spotpy/examples/tutorial_parallel_computing_hymod.py 100
  - pip uninstall spotpy -y

jobs:
  include:
    - stage: Coveralls
      name: Report Coveralls
      after_success: python3 -m coveralls

    # Test Deploy source distribution
    - stage: deploy
      name: PyPi Test Deploy
      script: python3 setup.py sdist --formats=gztar bdist_wheel
      after_success:
       - python3 -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*